### PR TITLE
Fix the Haskell colors against haskell-vim.

### PR DESCRIPTION
**Pull request by rbong**
Relates to morhetz/gruvbox#190.

:robot: **This pull request has been automatically copied from morhetz#209** :robot:

### CODE REVIEW

**Comment by rbong** [comment]
The original PR has a lot of positive attention and the original issue seems important. I'm going to merge this in.

**Comment by mlopes** [comment]
@rbong did this fix it for you? I'm still seeing it with some odd colour. Here's a screenshot of how it looks in Haskell for me vs how it looks for example when looking at the source of gruvbox:

image

image

**Comment by goolord** [comment]
yeah this looks pretty hideous with haskell-nvim, i don't know that many people who regularly write haskell who use the default ftplugin

**Comment by rbong** [comment]
If someone wants to define some haskell-nvim highlight groups I will gladly merge it in. I'm not familiar with Haskell constructs so I'm not sure I can effectively solve this myself.

**Comment by goolord** [comment]
here's the highlight groups i use daily
<details>

```vim
hi! link haskelltype gruvboxyellow

hi! link haskellidentifier gruvboxgreen

hi! link haskellseparator gruvboxfg3
hi! link haskelldelimiter gruvboxfg3
hi! link haskelloperators gruvboxblue
hi! link haskellbacktick haskelloperators

hi! link haskellstatement gruvboxorange

hi! link haskellconditional gruvboxred
hi! link haskellkeyword gruvboxred
hi! link haskelllet gruvboxred
hi! link haskellwhere gruvboxred

hi! link haskelldefault gruvboxaqua
hi! link haskellbottom gruvboxaqua
hi! link haskellblockkeywords gruvboxaqua
hi! link haskellimportkeywords gruvboxaqua
hi! link haskelldeclkeyword gruvboxaqua
hi! link haskelldecl gruvboxaqua
hi! link haskellderiving gruvboxaqua
hi! link haskellassoctype gruvboxaqua

hi! link haskellnumber gruvboxpurple
hi! link haskellpragma gruvboxpurple

hi! link haskellstring gruvboxgreen
hi! link haskellchar gruvboxgreen
```
</details>


image

unfortunately, this looks nice with haskell-vim, but not great for the ftplugin that ships with vim. idk if there is precedence for supporting conflicting ftplugins like this, or if this would be better suited to being fixed upstream haskell-vim

**Comment by OnionHat** [comment]
@goolord how did you apply the changes? Sourcing vim and doing PlugUpdate doesn't seem to work.

**Comment by goolord** [comment]
@OnionHat I forked gruvbox, I think. I just use the default haskell ft plugin now.

**Comment by OnionHat** [comment]
@goolord thanks for the answer! Forking it and editing the part did not seem to work, oh well, but thanks again!

**Comment by goolord** [comment]
@OnionHat ah it looks like there are new syntax groups for the colors. (`GruvboxYellow` instead of `gruvboxyellow` etc?)

**Pull request merged**
